name: Run tasks

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tasks
        run: node run tasks
