name: Run tasks

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    env:
      VERCEL_HOST: ${{ vars.VERCEL_HOST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Use variables
        run: |
          echo "repository variable : ${{ env.VERCEL_HOST }}"

      - name: Install dependencies
        run: npm install

      - name: Run tasks
        run: npm run tasks
